---
parser: babel-eslint
extends:
- eslint:recommended
- plugin:react/recommended
plugins:
- flowtype
- react
- jest
overrides:
- files:
  - __tests__/**/*.spec.{js,jsx}
  env:
    jest: true
- files:
  - src/**/*.{js,jsx}
  env:
    node: false
env:
  browser: true
  es6: true
  node: true
parserOptions:
  sourceType: module
rules:
  react/react-in-jsx-scope: off
  object-shorthand: error
  no-lone-blocks: error
  no-lonely-if: error
  no-negated-in-lhs: error
  no-new-object: error
  no-octal: error
  no-new-require: error
  no-new-wrappers: error
  no-mixed-operators: error
  no-self-compare: error
  no-sequences: error
  no-spaced-func: error
  no-tabs: error
  no-undefined: error
  no-unneeded-ternary: error
  prefer-arrow-callback: error
  prefer-const: error
  space-before-blocks: error
  semi: error
